# Makefile for lib/math.
lib-y := libnucc.a
libnucc.a-obj-y := asin.o atan.o atan2.o ceil.o exp.o fabs.o floor.o fmod.o \
	       hugeval.o log.o log10.o pow.o s_rint.o sin.o sinh.o sqrt.o \
	       tan.o tanh.o

ccflags-y := -O -D__UKERNEL__

