lib-y := libnucc.a libnucc_16.a
libnucc.a-obj-y := int64/ misc/ rts/ string/
libnucc_16.a-obj-y := x86_16/

# Add generic part if exists (do not build just add to list). The path must be absolute.
libnucc.a-obj-y += $(srctree)/lib/libnucc.a
