# ok
header-y += auxvec.h
# ok
header-y += bitsperlong.h
# ok
header-y += errno-base.h
# ok
header-y += errno.h
# ok
header-y += fcntl.h 
# ok
header-y += ioctl.h

header-y += ioctls.h
header-y += ioctls-cmos.h
header-y += ioctls-disk.h
header-y += ioctls-file.h
header-y += ioctls-memory.h
header-y += ioctls-scsi.h
header-y += ioctls-sound.h
header-y += ioctls-svrctl.h
header-y += ioctls-tape.h
header-y += ioctls-tty.h

header-y += ipcbuf.h
header-y += mman-common.h
header-y += mman.h
header-y += msgbuf.h
header-y += param.h
header-y += poll.h
header-y += posix_types.h
header-y += sembuf.h
header-y += setup.h
header-y += shmbuf.h
header-y += shmparam.h
header-y += signal-defs.h
header-y += signal.h
header-y += socket.h
header-y += sockios.h
header-y += stat.h
header-y += statfs.h
header-y += swab.h
header-y += termbits.h
header-y += termios.h
header-y += types.h
header-y += ucontext.h
header-y += unistd.h

header-y += int-l64.h
header-y += int-ll64.h
header-y += resource.h
header-y += siginfo.h
