# Makefile for all audio drivers.
obj-y := framework/ es1370/ es1371/
# Oboslete?
obj-n :=  sb16/

subdir-y-flags := not-sort

# For rest of audio drivers
audio-framework := $(src)/framework
export audio-framework
