# Makefile for lib/other.
lib-y := libnucc.a
libnucc.a-obj-y := _pm_findproc.o adddma.o brk.o cprofile.o deldma.o devctl.o getdents.o getdma.o \
		   getnpid.o getnprocnr.o getpprocnr.o getprocnr.o getsigset.o getsysinfo.o lseek64.o \
		   mapdriver5.o mount.o reboot.o sbrk.o seekdir.o sprofile.o svrctl.o vm_dmacalls.o \
		   asynchio.o basename.o bcmp.o bcopy.o bzero.o configfile.o crypt.o ctermid.o cuserid.o \
		   environ.o errno.o fdopen.o ffs.o flock.o fslib.o fts.o fsversion.o getgrent.o getlogin.o \
		   getpagesize.o getpass.o getpwent.o getttyent.o getw.o hypot.o index.o itoa.o \
		   lock.o lrand.o lsearch.o memccpy.o mstats.o mtab.o nlist.o paramvalue.o peekpoke.o \
		   popen.o putenv.o putw.o random.o rindex.o setenv.o setgroups.o settimeofday.o stderr.o strdup.o \
		   strlcat.o strlcpy.o strtok_r.o swab.o sys_eniop.o sysconf.o syslog.o \
		   telldir.o termcap.o ttyname.o ttyslot.o v8regerror.o v8regexp.o v8regsub.o writev.o getnuid.o \
		   getngid.o vm_set_priv.o vm_query_exit.o minix_rs.o umount.o initgroups.o

ccflags-y := -D__UKERNEL__
