#
# According to linux one
#
include include/asm-generic/Kbuild.asm

# n/a header-y += boot.h
header-y += bootparam.h
# n/a header-y += debugreg.h
# n/a header-y += ldt.h
# n/a header-y += msr-index.h
# n/a header-y += prctl.h
# n/a header-y += ptrace-abi.h
# n/a header-y += sigcontext32.h
# n/a header-y += ucontext.h
# n/a header-y += processor-flags.h
 
# n/a header-y += e820.h
# n/a header-y += ist.h
# n/a header-y += mce.h
# n/a header-y += msr.h
# n/a header-y += mtrr.h
header-y += posix_types_32.h
header-y += posix_types_64.h
header-y += unistd_32.h
header-y += unistd_64.h
# n/a header-y += vm86.h
# n/a header-y += vsyscall.h
