lib-y := libnucc.a
libnucc.a-obj-y := abort.o assert.o atexit.o calloc.o clock.o errlist.o \
		   exit.o getenv.o malloc.o raise.o sigmisc.o signal.o \
		   strerror.o strtol.o system.o

ccflags-y := -D__UKERNEL__
