lib-y := libnucc.a
libnucc.a-obj-y := abort.o abs.o assert.o atexit.o atof.o atoi.o atol.o bsearch.o calloc.o \
	       chartab.o clock.o difftime.o div.o errlist.o exit.o ext_comp.o getenv.o \
	       isalnum.o isalpha.o isascii.o iscntrl.o isdigit.o isgraph.o islower.o \
	       isprint.o ispunct.o isspace.o isupper.o isxdigit.o labs.o ldiv.o localeconv.o \
	       malloc.o mblen.o mbstowcs.o mbtowc.o misc.o qsort.o raise.o rand.o setlocale.o \
	       sigmisc.o signal.o strcoll.o strcspn.o strerror.o strpbrk.o strspn.o strstr.o \
	       strtok.o strtol.o strxfrm.o system.o tolower.o toupper.o wcstombs.o wctomb.o

ccflags-y := -D__UKERNEL__
