# this directory implements these libraries
lib-y := libsys.a libdriver.a libtimers.a libnucc.a libutil.a

libsys.a-obj-y := syslib/ sysutil/
libdriver.a-obj-y := libdriver/
libtimers.a-obj-y := timers/
libnucc.a-obj-y := ansi/ ip/ math64/ other/ posix/ regex/ \
		   stdio/ stdtime/ sysvipc/
libutil.a-obj-y := util/
