obj-y := do_abort.o do_endksig.o do_getinfo.o do_mapdma.o do_privctl.o do_setalarm.o \
	 do_sprofile.o do_trace.o do_vdevio.o do_copy.o do_exec.o do_getksig.o \
	 do_memset.o do_profbuf.o do_setgrant.o do_stime.o do_umap.o do_vmctl.o \
	 do_cprofile.o do_exit.o do_irqctl.o do_newmap.o do_safecopy.o do_sigreturn.o \
	 do_sysctl.o do_unused.o do_devio.o do_fork.o do_kill.o do_nice.o \
	 do_segctl.o do_sigsend.o do_times.o do_vcopy.o do_vtimer.o do_runctl.o

ccflags-y := -D__KERNEL__

create-builtin := y
