lib-y := libnucc.a
libnucc.a-obj-y := _exit.o _pm_findproc.o access.o adddma.o alarm.o brk.o cfgetispeed.o cfgetospeed.o \
	cfsetispeed.o cfsetospeed.o chdir.o chmod.o chown.o chroot.o close.o closedir.o cprofile.o \
	creat.o deldma.o devctl.o dup.o dup2.o execl.o execle.o execlp.o execv.o execve.o execvp.o \
	fchmod.o fchown.o fcntl.o fork.o fpathconf.o fstat.o fstatfs.o getcwd.o getdents.o getdma.o \
	getegid.o geteuid.o getgid.o getgroups.o getnpid.o getnprocnr.o getpgrp.o getpid.o getppid.o \
	getpprocnr.o getprocnr.o getsigset.o getsysinfo.o getuid.o ioctl.o isatty.o kill.o killpg.o \
	link.o lseek.o lseek64.o lstat.o mapdriver5.o mkdir.o mkfifo.o mknod.o mmap.o  mount.o open.o \
	opendir.o pathconf.o pause.o pipe.o ptrace.o read.o readdir.o readlink.o reboot.o rename.o \
	rewinddir.o rmdir.o sbrk.o seekdir.o select.o setgid.o setsid.o setuid.o sigaction.o sigaddset.o \
	sigdelset.o sigemptyset.o sigfillset.o sigismember.o sigpending.o sigprocmask.o sigreturn.o \
	sigsuspend.o sleep.o sprofile.o stat.o stime.o svrctl.o symlink.o sync.o sysuname.o tcdrain.o \
	tcflow.o tcflush.o tcgetattr.o tcsendbreak.o tcsetattr.o time.o times.o truncate.o umask.o \
	umount.o uname.o unlink.o utime.o vm_dmacalls.o wait.o waitpid.o write.o
